#!/usr/bin/env python3
"""
Auto-generate SUMMARY.md for mdbook based on directory structure.
This script scans the docs directory and creates a table of contents.
"""

import os
import re
from pathlib import Path
from typing import List, Tuple

def get_title_from_file(file_path: Path) -> str:
    """Extract title from markdown file's first heading."""
    try:
        with open(file_path, 'r', encoding='utf-8') as f:
            for line in f:
                # Look for # Title format
                match = re.match(r'^#\s+(.+)$', line.strip())
                if match:
                    return match.group(1)
    except Exception:
        pass
    
    # Fallback to filename
    return file_path.stem.replace('-', ' ').replace('_', ' ').title()

def should_include_file(file_path: Path, docs_dir: Path) -> bool:
    """Determine if a file should be included in the summary."""
    # Skip SUMMARY.md itself
    if file_path.name == 'SUMMARY.md':
        return False
    
    # Skip README.md (it's in the root, not for the docs)
    if file_path.name == 'README.md':
        return False
    
    # Skip introduction.md (manually added to summary)
    if file_path.name == 'introduction.md':
        return False
    
    # Only include .md files
    if file_path.suffix != '.md':
        return False
    
    return True

def get_sort_key(path: Path) -> Tuple[int, str]:
    """
    Generate a sort key for ordering files.
    Priority: index.md first, then alphabetical by name.
    """
    name = path.name.lower()
    
    # index.md always comes first
    if name == 'index.md':
        return (0, name)
    
    # README.md comes second  
    if name == 'readme.md':
        return (1, name)
    
    # Everything else alphabetically
    return (2, name)

def scan_directory(directory: Path, docs_dir: Path, indent: int = 0, parent_has_index: bool = False) -> List[str]:
    """Recursively scan directory and generate summary lines."""
    lines = []
    
    if not directory.is_dir():
        return lines
    
    # Get all items in directory
    items = sorted(directory.iterdir(), key=get_sort_key)
    
    # Separate files and directories
    files = [item for item in items if item.is_file() and should_include_file(item, docs_dir)]
    directories = [item for item in items if item.is_dir() and not item.name.startswith('.')]
    
    # Process files first (but skip index.md if parent already added it)
    for file_path in files:
        # Skip index.md at root level (it's the book title)
        if file_path.name == 'index.md' and indent == 0:
            continue
        
        # Skip index.md files in subdirectories since they're used as section headers
        if file_path.name == 'index.md' and parent_has_index:
            continue
            
        rel_path = file_path.relative_to(docs_dir)
        title = get_title_from_file(file_path)
        indent_str = '  ' * indent
        lines.append(f'{indent_str}- [{title}](<{rel_path.as_posix()}>)')
    
    # Then process subdirectories
    for subdir in directories:
        # Get the index.md from the subdirectory if it exists
        index_file = subdir / 'index.md'
        
        if index_file.exists():
            rel_path = index_file.relative_to(docs_dir)
            title = get_title_from_file(index_file)
            indent_str = '  ' * indent
            lines.append(f'{indent_str}- [{title}](<{rel_path.as_posix()}>)')
            
            # Recursively process subdirectory contents (skip the index.md we just added)
            subdir_lines = scan_directory(subdir, docs_dir, indent + 1, parent_has_index=True)
            lines.extend(subdir_lines)
        else:
            # No index.md, just process contents at same level
            subdir_lines = scan_directory(subdir, docs_dir, indent, parent_has_index=False)
            lines.extend(subdir_lines)
    
    return lines

def generate_summary(docs_dir: Path) -> str:
    """Generate the complete SUMMARY.md content."""
    # Start with the book title
    index_file = docs_dir / 'index.md'
    book_title = 'Driftless Documentation'
    
    if index_file.exists():
        book_title = get_title_from_file(index_file)
    
    lines = [
        '<!-- Auto-generated by scripts/generate-summary.py - do not edit manually! -->',
        '',
        f'[{book_title}](<index.md>)',
        '- [Introduction](<introduction.md>)'
    ]
    
    # Scan the docs directory
    content_lines = scan_directory(docs_dir, docs_dir)
    lines.extend(content_lines)
    
    return '\n'.join(lines) + '\n'

def main():
    """Main entry point."""
    # Get the docs directory
    script_dir = Path(__file__).parent
    repo_root = script_dir.parent
    docs_dir = repo_root / 'docs'
    
    if not docs_dir.exists():
        print(f"Error: docs directory not found at {docs_dir}")
        return 1
    
    # Generate the summary
    summary_content = generate_summary(docs_dir)
    
    # Write to SUMMARY.md
    summary_file = docs_dir / 'SUMMARY.md'
    try:
        with open(summary_file, 'w', encoding='utf-8') as f:
            f.write(summary_content)
        print(f"✅ Generated {summary_file}")
    except IOError as e:
        print(f"❌ Error writing {summary_file}: {e}")
        return 1
    
    return 0

if __name__ == '__main__':
    exit(main())
